name: 同步上游 GitHub 仓库
on:
  push:
  schedule:
    - cron: '17 * * * *'
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # 👇 这里必须用 v2.3.5 才能自动执行！
      - uses: actions/checkout@v2.3.5

      - name: Merge upstream
        run: |
          git config --global user.name 'robert34'
          git config --global user.email 'lfyuuanwuqu@163.com'
          git pull --unshallow
          git remote add upstream https://github.com/6dylan6/jdpro.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          git fetch upstream --tags
          git push --tags
